Adding Gov docs and updating community guides
berachain/docs-old pull request #274
Opened 2024-08-29 13:58 UTC by adam0x7

## Description

What changes are made in this PR? Is it a feature or a bug fix?
Adding Gov docs and updating community guides
Does it close a specific issue?

Example:

```
Closes #1
```

## Contribution

- [ ] I have followed the [Development Workflow](https://github.com/berachain/docs/blob/main/CONTRIBUTING.md#development-workflow)
- [ ] I have read the [CODE OF CONDUCT](https://github.com/berachain/docs/blob/main/CODE_OF_CONDUCT.md)

Let us know your wallet address/ENS:

```
0xYourAddress
```

2024-08-29 16:35 UTC, corduroybera requested changes

2024-08-29 16:35 UTC, corduroybera commented on apps/core/content/learn/governance/gauges.md
> +   - If declined: Marked as defeated, allowing for a new proposal after addressing concerns
These are testnet placeholders, they may or may not change before governance is live

2024-08-29 16:35 UTC, corduroybera commented on apps/core/content/learn/governance/index.md
> +For a detailed walkthrough of creating a governance proposal, including code examples and step-by-step instructions, please refer to our [full tutorial](https://github.com/berachain/rewards-vault-tut
link 404s

2024-08-29 16:35 UTC, corduroybera commented on apps/core/content/learn/governance/gauges.md
> +This mechanism is central to Berachain's [Reward Vaults](https://docs.berachain.com/developers/contracts/rewards-vault) system.
```suggestion
This mechanism is central to Berachain's [Reward Vaults](/developers/contracts/rewards-vault) system.
```

Switch to relative

2024-08-29 16:35 UTC, corduroybera commented on apps/core/.vitepress/sidebar.ts
> +        { text: "Burn $BGT", link: "/learn/guides/burn-bgt" },
Dead links showing in sidebar

2024-08-29 16:35 UTC, corduroybera commented on apps/core/content/learn/governance/gauges.md
This page should have some reference to how to create a reward vault. Maybe as a step 0 or pre-requisite, just to make sure it's clear how they get it deployed prior to proposal

2024-08-30 13:57 UTC, codingwithmanny commented on apps/core/.vitepress/sidebar.ts
> +          text: "Delegate BGT To Validator ",
```suggestion
          text: "Delegate BGT To Validator",
```

2024-08-30 13:57 UTC, codingwithmanny commented on apps/core/.vitepress/sidebar.ts
> +          text: "Create PoL Gauge Proposal  ",
```suggestion
          text: "Create PoL Gauge Proposal",
```

2024-08-30 14:00 UTC, codingwithmanny commented on apps/core/content/developers/guides/community-guides.md
> +| Berachain Governance Proposal | [GitHub](https://github.com/berachain/guides/tree/main/apps/berachain-governance-proposal) |
```suggestion
| Berachain Governance Proposal For Reward Vaults | [GitHub](https://github.com/berachain/guides/tree/main/apps/berachain-governance-proposal) |
```

2024-08-30 14:24 UTC, codingwithmanny commented on apps/core/content/.assets/governance-process.png
Put this under `apps/core/content/public`

2024-08-30 15:06 UTC, codingwithmanny commented on apps/core/content/learn/governance/gauges.md
Revise page to be `rewardvaults.md` and adjust sidebar.

2024-08-30 15:07 UTC, codingwithmanny commented on apps/core/content/learn/governance/gauges.md
> +Berachain's Proof of Liquidity (PoL) consensus mechanism allows protocols to bootstrap their liquidity by receiving Berachain Governance Token (BGT) emissions from validators. This process is facilit
Any reference to tokens, make the format `$BGT` as an example.

2024-08-30 15:08 UTC, codingwithmanny commented on apps/core/content/learn/governance/gauges.md
Agree that there should be some links. The only issue is that there really isn't a UI version of things, but perhaps mention that if you'd like to do it programmatically.. see here..

2024-08-30 15:11 UTC, codingwithmanny commented on apps/core/content/learn/governance/gauges.md
> +   - If declined: Marked as defeated, allowing for a new proposal after addressing concerns
Agree would just add a section under the title with something like:

```md
### Governance Process for Whitelisting

:::warning
**NOTE:** The values mentioned are currently on Testnet which are placeholders subject to change and may not reflect the values used for Mainnet.
:::
```

2024-08-30 15:13 UTC, codingwithmanny commented on apps/core/content/learn/governance/index.md
> +Berachain's Governance system uses BGT to allow token holders to make important decisions about core functions of Proof of Liquidity & our core dapps. Here's a few examples of what governance can be
```suggestion
Berachain's Governance system uses `$BGT` to allow token holders to make important decisions about core functions of Proof-of-Liquidity & our core dapps. Here are a few examples of what governance can be used for:
```

2024-08-30 15:21 UTC, codingwithmanny commented on apps/core/content/learn/governance/index.md
> +- Whitelisting Rewards Vaults for BGT emissions
Isn't the first related to the last item?

```suggestion
1. `$HONEY` minting parameters (e.g., eligible collateral assets, minting rates)
2. Native dApp governance for BEX, Berps, & Bend (e.g., changes to Bend's interest rate model)
3. Whitelisting Rewards Vaults for `$BGT` emissions
```

2024-08-30 15:23 UTC, codingwithmanny commented on apps/core/content/learn/governance/index.md
> +1. **Proposal Creation**: Any user with sufficient voting power (at least 1000 $BGT) can create a governance proposal.
```suggestion
1. **Proposal Creation**: Any user with sufficient voting power (meeting a minimum amount of `$BGT`) can create a governance proposal.
```

2024-08-30 15:31 UTC, codingwithmanny commented on apps/core/content/learn/governance/index.md
> +## Governance Process
This section I would remove specifics on amounts of BGT and number of hours and add a section just after the steps with Testnet values.

Example.

```md
## Governance Process

The governance process on Berachain follows several stages.

![Governance Process](/assets/governance-process.png)

1. **Proposal Creation**: Any user with sufficient voting power (meeting a minimum amount of `$BGT`) can create a governance proposal.

...

### Testnet Governance Values

| State | Criteria |
| ----------- | ----------- |
| Proposal Creation | 1000 `$BGT` Required |
| Pending State | 3-hour waiting period |
| Proposal Outcome | 2 billion `$BGT` required reach quorum  |
...
```

2024-08-30 15:32 UTC, codingwithmanny commented on apps/core/content/learn/governance/index.md
> +1. **Ensure Sufficient Voting Power**: You need at least 1000 $BGT, either owned directly or delegated to you by other token holders.
See above comment and see where you can consolidate specific values to one section, aka remove 1000 $BGT.

2024-08-30 18:30 UTC, adam0x7 commented on apps/core/.vitepress/sidebar.ts
> +          text: "Delegate BGT To Validator ",
airdrop farmer comment

2024-08-30 18:31 UTC, adam0x7 commented on apps/core/.vitepress/sidebar.ts
> +          text: "Create PoL Gauge Proposal  ",
airdrop farmer comment

2024-09-06 09:44 UTC, codingwithmanny commented on apps/core/content/learn/governance/rewardvault.md
> +   - If declined: Marked as defeated, allowing for a new proposal after addressing concerns
Review this section to remove the numbers (3-hour, 2-day, 1000 BGT) and refer to other page for values.

2024-09-06 22:07 UTC, codingwithmanny approved these changes
LGTM

2024-09-06 23:01 UTC, codingwithmanny requested changes
Add versioning

2024-09-10 06:31 UTC, merged